// FONTE: WF6 - Bella WhatsApp (ATIVO).json → node "Montar" (n8n-nodes-base.code)
// Extraído por scripts/extract_prompts.mjs — a fonte da verdade é o servidor n8n.
// ATENÇÃO: strings de prompt são double-quoted; nunca inserir " sem escape ao editar.

const cfg = $('Config').first().json;
const f = $('Filtrar').first().json;
if (!f.texto) return [{ json: { pular_llm: true, resposta_direta: 'Oi! Por enquanto eu entendo mensagens de texto 🙂 Escreva o pedido aqui, ou mande por e-mail para ssysbot@gmail.com — lá eu leio foto e PDF também. — Bella', body: { contents: [{ role: 'user', parts: [{ text: 'responda apenas: ok' }] }], generationConfig: { temperature: 0, maxOutputTokens: 5 } } } }];
const reqs = $('Ler REQUISITOS').all().map(i => i.json);
const pedidos = $('Ler PEDIDOS').all().map(i => i.json).filter(p => p && p['Nº PEDIDO']);
let mem = [];
try { mem = $('Ler MEMORIA').all().map(i => i.json).filter(m => m && m.NUMERO && String(m.NUMERO) === String(f.remetente)); } catch (e) {}
const conversa = mem.slice(-8).map(m => (m.PAPEL || '?') + ': ' + String(m.MENSAGEM || '').slice(0, 300)).join('\n');
const pend = pedidos.filter(p => String(p['REMETENTE'] || '').indexOf(f.remetente) >= 0 && p['STATUS'] === 'PENDENTE');
const pendTxt = pend.map(p => 'pedido ' + p['Nº PEDIDO'] + ' item ' + p['ITEM Nº'] + ': "' + p['ITEM'] + '" (quant: ' + (p['QUANT.'] || '?') + ' ' + (p['UNID.'] || '') + ') — falta: ' + p['PENDÊNCIAS']).join('\n');
const tabela = reqs.map(r => '- ' + r['CATEGORIA'] + ' (palavras-chave: ' + r['PALAVRAS-CHAVE'] + ') => obrigatórios: ' + r['CAMPOS OBRIGATÓRIOS']).join('\n');
const SYSTEM = "Você é a Bella, assistente de compras da construtora Prisbel, conversando por WhatsApp. Sua tarefa: classificar a MENSAGEM usando a CONVERSA RECENTE e os ITENS PENDENTES como contexto e, se for pedido ou complemento, extrair os dados. Responda SOMENTE com JSON válido: {\"intencao\": \"PEDIDO\"|\"COMPLEMENTO\"|\"STATUS\"|\"LOCACAO\"|\"OUTRO\", \"num_pedido_consultado\": numero|null, \"pedido\": {\"obra\": \"nome\"|null, \"urgente\": true|false, \"motivo_urgencia\": \"texto\"|null, \"itens\": [{\"descricao\": \"...\", \"quantidade\": numero|null, \"unidade\": \"...\", \"categoria\": \"da tabela\", \"campos_faltantes\": [\"...\"]}]} | null, \"complementos\": [{\"num_pedido\": numero, \"item_num\": numero, \"descricao_extra\": \"texto a acrescentar\"|null, \"quantidade\": numero|null, \"unidade\": \"...\"|null, \"obra\": \"...\"|null, \"motivo_urgencia\": \"...\"|null, \"pendencias_restantes\": [\"...\"]}] | null}. Definições: PEDIDO = solicita compra de materiais NOVOS; COMPLEMENTO = a mensagem fornece dados que faltavam em itens da lista ITENS PENDENTES — se a Bella acabou de pedir o que falta na CONVERSA RECENTE e a mensagem responde isso, é COMPLEMENTO, NUNCA um pedido novo; STATUS = pergunta sobre andamento de pedido ou cotação; LOCACAO = resposta sobre devolver/renovar equipamentos locados; OUTRO = qualquer outra coisa. Regras de COMPLEMENTO: preencha apenas os campos que a mensagem informa; TODA especificação nova do item (litragem, tipo, cor, dimensão, modelo, tamanho, CA, marca) deve ir em descricao_extra para ficar registrada na descrição — nunca descarte uma informação dada; em pendencias_restantes liste as pendências do item que AINDA ficaram sem resposta (lista vazia se resolveu tudo). Regras de itens: campos obrigatórios ausentes da categoria entram em campos_faltantes; unidade implícita na descrição (sacos, latas, barras, rolos, pacotes, caixas, pares, kg, metros) é unidade VÁLIDA — saco é a unidade padrão de cimento, argamassa, gesso e cal; aplique só os campos que fazem sentido ao subtipo; urgência com justificativa de prazo/cronograma conta como motivo; número de requisição não é quantidade. NUNCA invente dados. REGRAS ADICIONAIS: (a) a descricao de cada item deve preservar TODAS as especificações mencionadas na mensagem — dimensões, classe, resistência, bitola, cor, marca, modelo (ex.: 'blocos de concreto estrutural 14x19x39 4,5 MPa', nunca só 'blocos de concreto'); (b) designações comerciais que JÁ SÃO a classe do produto não geram pendência: CP2/CP II/CP III/CP IV/CP V (cimento), AC1/AC2/AC3 (argamassa colante), CA-50/CA-60 (vergalhão) — se presentes, o campo classe/tipo está atendido; (c) em COMPLEMENTO, todo dado técnico novo (MPa, classe, cor, dimensão) DEVE aparecer em descricao_extra.";
const user = 'TABELA DE CATEGORIAS:\n' + tabela + '\n\nITENS PENDENTES DESTE REMETENTE:\n' + (pendTxt || '(nenhum)') + '\n\nCONVERSA RECENTE:\n' + (conversa || '(primeira mensagem)') + '\n\nREMETENTE: ' + (f.nome || f.remetente) + '\n\nMENSAGEM:\n' + f.texto;
return [{ json: { pular_llm: false, body: { system_instruction: { parts: [{ text: SYSTEM }] }, contents: [{ role: 'user', parts: [{ text: user }] }], generationConfig: { temperature: 0, maxOutputTokens: 4096, responseMimeType: 'application/json', thinkingConfig: { thinkingBudget: 0 } } } } }];
